# Generated by Django 4.1 on 2022-11-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recovered',
            new_name='Recovered_Patient',
        ),
    ]
