# Generated by Django 4.1 on 2022-11-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_died'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Died',
            new_name='Died_Patient',
        ),
    ]
