# Generated by Django 4.1 on 2022-11-30 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_new_total_number_died_patients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='died_patient',
            name='recorded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='new_total_number_died_patients',
            name='recorded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='new_total_number_positive_patients',
            name='recorded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='new_total_number_recovered_patients',
            name='recorded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recovered_patient',
            name='recorded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
