# Generated by Django 4.1 on 2022-12-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_rename_new_total_number_recovered_patients_new_total_number_died_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Death_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
                ('recovered_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Death_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
                ('death_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Positive_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Recovered_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
                ('recovered_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Positive_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recovered_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
                ('recovered_date', models.DateField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='New_Total_Number_Died_Patient',
        ),
        migrations.DeleteModel(
            name='New_Total_Number_Positive_Patient',
        ),
        migrations.DeleteModel(
            name='New_Total_Number_Recovered_Patient',
        ),
        migrations.DeleteModel(
            name='Total_Died_Patient',
        ),
        migrations.DeleteModel(
            name='Total_Positive_Patient',
        ),
        migrations.DeleteModel(
            name='Total_Recovered_Patient',
        ),
    ]
