# Generated by Django 4.1 on 2022-12-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_death_detail_new_death_detail_new_positive_detail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Death_Detail',
        ),
        migrations.DeleteModel(
            name='New_Death_Detail',
        ),
        migrations.DeleteModel(
            name='New_Positive_Detail',
        ),
        migrations.DeleteModel(
            name='New_Recovered_Detail',
        ),
        migrations.DeleteModel(
            name='Patient_Detail',
        ),
        migrations.DeleteModel(
            name='Positive_Detail',
        ),
        migrations.DeleteModel(
            name='Recovered_Detail',
        ),
    ]
