# Generated by Django 4.1 on 2022-12-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mild_Case_Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
                ('recovered_date', models.DateField(blank=True)),
                ('population', models.FloatField(default=1)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Moderate_Case_Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
                ('recovered_date', models.DateField(blank=True)),
                ('population', models.FloatField(default=1)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Severe_Case_Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('barangay', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_admitted', models.DateField(blank=True)),
                ('recovered_date', models.DateField(blank=True)),
                ('population', models.FloatField(default=1)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
    ]
