# Generated by Django 4.1 on 2022-12-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mild_case_patient',
            name='recovered_date',
        ),
        migrations.RemoveField(
            model_name='moderate_case_patient',
            name='recovered_date',
        ),
        migrations.RemoveField(
            model_name='severe_case_patient',
            name='recovered_date',
        ),
    ]
