# Generated by Django 4.1 on 2022-11-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_total_positive_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_Total_Number_Recovered_Patients',
            new_name='New_Total_Number_Died_Patient',
        ),
        migrations.RenameModel(
            old_name='Died_Patient',
            new_name='New_Total_Number_Positive_Patient',
        ),
        migrations.RenameModel(
            old_name='New_Total_Number_Positive_Patients',
            new_name='New_Total_Number_Recovered_Patient',
        ),
        migrations.RenameModel(
            old_name='New_Total_Number_Died_Patients',
            new_name='Total_Died_Patient',
        ),
        migrations.RenameModel(
            old_name='Recovered_Patient',
            new_name='Total_Recovered_Patient',
        ),
    ]
