# Generated by Django 4.1 on 2022-11-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Patient', '0004_alter_patient_date_admitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_admitted',
            field=models.DateField(blank=True, null=True, verbose_name='Date Admitted (mm/dd/yyyy):'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
