# Generated by Django 4.1 on 2022-11-20 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Patient', '0005_alter_patient_date_admitted_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_admitted',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 20, 2, 19, 35, 575666, tzinfo=datetime.timezone.utc), verbose_name='Date Admitted (mm/dd/yyyy):'),
            preserve_default=False,
        ),
    ]
