# Generated by Django 4.1 on 2022-11-25 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Patient', '0008_alter_patient_recorded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='recorded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
