# Generated by Django 4.1 on 2022-11-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Patient', '0009_alter_patient_recorded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
    ]
