# Generated by Django 4.1 on 2022-12-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Patient', '0012_death_detail_new_death_detail_new_positive_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='death_detail',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='death_detail',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='death_detail',
            name='population',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='new_death_detail',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='new_death_detail',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='new_death_detail',
            name='population',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='new_positive_detail',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='new_positive_detail',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='new_positive_detail',
            name='population',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='new_recovered_detail',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='new_recovered_detail',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='new_recovered_detail',
            name='population',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='patient_detail',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient_detail',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient_detail',
            name='population',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='positive_detail',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='positive_detail',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='positive_detail',
            name='population',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='recovered_detail',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recovered_detail',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recovered_detail',
            name='population',
            field=models.FloatField(default=1),
        ),
    ]
